# Generated by Django 5.2.8 on 2025-11-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('laboratorio', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('requiere_receta', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('instrucciones', models.TextField(blank=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.historialmedico')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicamento.medicamento')),
            ],
        ),
    ]
